// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("sigsci");

/**
 * URL override for testing
 */
export declare const apiUrl: string | undefined;
Object.defineProperty(exports, "apiUrl", {
    get() {
        return __config.get("apiUrl");
    },
    enumerable: true,
});

/**
 * The token used for authentication specify either the password or the token
 */
export declare const authToken: string | undefined;
Object.defineProperty(exports, "authToken", {
    get() {
        return __config.get("authToken");
    },
    enumerable: true,
});

/**
 * Corp short name (id)
 */
export declare const corp: string | undefined;
Object.defineProperty(exports, "corp", {
    get() {
        return __config.get("corp");
    },
    enumerable: true,
});

/**
 * The email to be used for authentication
 */
export declare const email: string | undefined;
Object.defineProperty(exports, "email", {
    get() {
        return __config.get("email");
    },
    enumerable: true,
});

/**
 * The Fastly API key used for deploying Signal Sciences as a Fastly edge security service. For edge deployment service
 * calls, the Fastly key must have write access to the given service.
 */
export declare const fastlyApiKey: string | undefined;
Object.defineProperty(exports, "fastlyApiKey", {
    get() {
        return __config.get("fastlyApiKey");
    },
    enumerable: true,
});

/**
 * The password used to for authentication specify either the password or the token
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * Enable validation of API credentials during provider initialization. Default is true.
 */
export declare const validate: boolean | undefined;
Object.defineProperty(exports, "validate", {
    get() {
        return __config.getObject<boolean>("validate");
    },
    enumerable: true,
});

