// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CorpList extends pulumi.CustomResource {
    /**
     * Get an existing CorpList resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CorpListState, opts?: pulumi.CustomResourceOptions): CorpList {
        return new CorpList(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sigsci:index/corpList:CorpList';

    /**
     * Returns true if the given object is an instance of CorpList.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CorpList {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CorpList.__pulumiType;
    }

    public readonly corpListId!: pulumi.Output<string>;
    /**
     * Optional list description
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * List entries
     */
    public readonly entries!: pulumi.Output<string[]>;
    /**
     * Descriptive list name
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * List types (string, ip, country, wildcard, signal)
     */
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a CorpList resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CorpListArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CorpListArgs | CorpListState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CorpListState | undefined;
            resourceInputs["corpListId"] = state ? state.corpListId : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["entries"] = state ? state.entries : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as CorpListArgs | undefined;
            if ((!args || args.entries === undefined) && !opts.urn) {
                throw new Error("Missing required property 'entries'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["corpListId"] = args ? args.corpListId : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["entries"] = args ? args.entries : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CorpList.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering CorpList resources.
 */
export interface CorpListState {
    corpListId?: pulumi.Input<string>;
    /**
     * Optional list description
     */
    description?: pulumi.Input<string>;
    /**
     * List entries
     */
    entries?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Descriptive list name
     */
    name?: pulumi.Input<string>;
    /**
     * List types (string, ip, country, wildcard, signal)
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CorpList resource.
 */
export interface CorpListArgs {
    corpListId?: pulumi.Input<string>;
    /**
     * Optional list description
     */
    description?: pulumi.Input<string>;
    /**
     * List entries
     */
    entries: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Descriptive list name
     */
    name?: pulumi.Input<string>;
    /**
     * List types (string, ip, country, wildcard, signal)
     */
    type: pulumi.Input<string>;
}
