// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class CorpRule extends pulumi.CustomResource {
    /**
     * Get an existing CorpRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CorpRuleState, opts?: pulumi.CustomResourceOptions): CorpRule {
        return new CorpRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sigsci:index/corpRule:CorpRule';

    /**
     * Returns true if the given object is an instance of CorpRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CorpRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CorpRule.__pulumiType;
    }

    /**
     * Actions
     */
    public readonly actions!: pulumi.Output<outputs.CorpRuleAction[]>;
    /**
     * Conditions
     */
    public readonly conditions!: pulumi.Output<outputs.CorpRuleCondition[]>;
    public readonly corpRuleId!: pulumi.Output<string>;
    /**
     * Whether the rule is applied to all sites or to specific sites. (global, specificSites)
     */
    public readonly corpScope!: pulumi.Output<string>;
    /**
     * enable the rule
     */
    public readonly enabled!: pulumi.Output<boolean>;
    /**
     * Date the rule will automatically be disabled. If rule is always enabled, will return empty string
     */
    public readonly expiration!: pulumi.Output<string>;
    /**
     * Conditions that must be matched when evaluating the request (all, any)
     */
    public readonly groupOperator!: pulumi.Output<string>;
    /**
     * Description of the rule
     */
    public readonly reason!: pulumi.Output<string>;
    /**
     * Indicates whether to store the logs for requests that match the rule's conditions (sampled) or not store them (none).
     * This field is only available for rules of type `request`. Not valid for `signal`.
     */
    public readonly requestlogging!: pulumi.Output<string | undefined>;
    /**
     * The signal id of the signal being excluded
     */
    public readonly signal!: pulumi.Output<string | undefined>;
    /**
     * Sites with the rule available. Rules with a global corpScope will return '[]'.
     */
    public readonly siteShortNames!: pulumi.Output<string[] | undefined>;
    /**
     * Type of rule (request, signal)
     */
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a CorpRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CorpRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CorpRuleArgs | CorpRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CorpRuleState | undefined;
            resourceInputs["actions"] = state ? state.actions : undefined;
            resourceInputs["conditions"] = state ? state.conditions : undefined;
            resourceInputs["corpRuleId"] = state ? state.corpRuleId : undefined;
            resourceInputs["corpScope"] = state ? state.corpScope : undefined;
            resourceInputs["enabled"] = state ? state.enabled : undefined;
            resourceInputs["expiration"] = state ? state.expiration : undefined;
            resourceInputs["groupOperator"] = state ? state.groupOperator : undefined;
            resourceInputs["reason"] = state ? state.reason : undefined;
            resourceInputs["requestlogging"] = state ? state.requestlogging : undefined;
            resourceInputs["signal"] = state ? state.signal : undefined;
            resourceInputs["siteShortNames"] = state ? state.siteShortNames : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as CorpRuleArgs | undefined;
            if ((!args || args.actions === undefined) && !opts.urn) {
                throw new Error("Missing required property 'actions'");
            }
            if ((!args || args.conditions === undefined) && !opts.urn) {
                throw new Error("Missing required property 'conditions'");
            }
            if ((!args || args.corpScope === undefined) && !opts.urn) {
                throw new Error("Missing required property 'corpScope'");
            }
            if ((!args || args.enabled === undefined) && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            if ((!args || args.expiration === undefined) && !opts.urn) {
                throw new Error("Missing required property 'expiration'");
            }
            if ((!args || args.groupOperator === undefined) && !opts.urn) {
                throw new Error("Missing required property 'groupOperator'");
            }
            if ((!args || args.reason === undefined) && !opts.urn) {
                throw new Error("Missing required property 'reason'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["actions"] = args ? args.actions : undefined;
            resourceInputs["conditions"] = args ? args.conditions : undefined;
            resourceInputs["corpRuleId"] = args ? args.corpRuleId : undefined;
            resourceInputs["corpScope"] = args ? args.corpScope : undefined;
            resourceInputs["enabled"] = args ? args.enabled : undefined;
            resourceInputs["expiration"] = args ? args.expiration : undefined;
            resourceInputs["groupOperator"] = args ? args.groupOperator : undefined;
            resourceInputs["reason"] = args ? args.reason : undefined;
            resourceInputs["requestlogging"] = args ? args.requestlogging : undefined;
            resourceInputs["signal"] = args ? args.signal : undefined;
            resourceInputs["siteShortNames"] = args ? args.siteShortNames : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CorpRule.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering CorpRule resources.
 */
export interface CorpRuleState {
    /**
     * Actions
     */
    actions?: pulumi.Input<pulumi.Input<inputs.CorpRuleAction>[]>;
    /**
     * Conditions
     */
    conditions?: pulumi.Input<pulumi.Input<inputs.CorpRuleCondition>[]>;
    corpRuleId?: pulumi.Input<string>;
    /**
     * Whether the rule is applied to all sites or to specific sites. (global, specificSites)
     */
    corpScope?: pulumi.Input<string>;
    /**
     * enable the rule
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Date the rule will automatically be disabled. If rule is always enabled, will return empty string
     */
    expiration?: pulumi.Input<string>;
    /**
     * Conditions that must be matched when evaluating the request (all, any)
     */
    groupOperator?: pulumi.Input<string>;
    /**
     * Description of the rule
     */
    reason?: pulumi.Input<string>;
    /**
     * Indicates whether to store the logs for requests that match the rule's conditions (sampled) or not store them (none).
     * This field is only available for rules of type `request`. Not valid for `signal`.
     */
    requestlogging?: pulumi.Input<string>;
    /**
     * The signal id of the signal being excluded
     */
    signal?: pulumi.Input<string>;
    /**
     * Sites with the rule available. Rules with a global corpScope will return '[]'.
     */
    siteShortNames?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Type of rule (request, signal)
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CorpRule resource.
 */
export interface CorpRuleArgs {
    /**
     * Actions
     */
    actions: pulumi.Input<pulumi.Input<inputs.CorpRuleAction>[]>;
    /**
     * Conditions
     */
    conditions: pulumi.Input<pulumi.Input<inputs.CorpRuleCondition>[]>;
    corpRuleId?: pulumi.Input<string>;
    /**
     * Whether the rule is applied to all sites or to specific sites. (global, specificSites)
     */
    corpScope: pulumi.Input<string>;
    /**
     * enable the rule
     */
    enabled: pulumi.Input<boolean>;
    /**
     * Date the rule will automatically be disabled. If rule is always enabled, will return empty string
     */
    expiration: pulumi.Input<string>;
    /**
     * Conditions that must be matched when evaluating the request (all, any)
     */
    groupOperator: pulumi.Input<string>;
    /**
     * Description of the rule
     */
    reason: pulumi.Input<string>;
    /**
     * Indicates whether to store the logs for requests that match the rule's conditions (sampled) or not store them (none).
     * This field is only available for rules of type `request`. Not valid for `signal`.
     */
    requestlogging?: pulumi.Input<string>;
    /**
     * The signal id of the signal being excluded
     */
    signal?: pulumi.Input<string>;
    /**
     * Sites with the rule available. Rules with a global corpScope will return '[]'.
     */
    siteShortNames?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Type of rule (request, signal)
     */
    type: pulumi.Input<string>;
}
