// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EdgeDeploymentService extends pulumi.CustomResource {
    /**
     * Get an existing EdgeDeploymentService resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EdgeDeploymentServiceState, opts?: pulumi.CustomResourceOptions): EdgeDeploymentService {
        return new EdgeDeploymentService(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sigsci:index/edgeDeploymentService:EdgeDeploymentService';

    /**
     * Returns true if the given object is an instance of EdgeDeploymentService.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EdgeDeploymentService {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EdgeDeploymentService.__pulumiType;
    }

    /**
     * activate Fastly service version after clone. Possible values are true or false. Defaults to true.
     */
    public readonly activateVersion!: pulumi.Output<boolean | undefined>;
    /**
     * enable to prevent Fastly-Client-IP from being overwritten by the NGWAF. Intended for advanced use cases. Defaults to
     * false.
     */
    public readonly customClientIp!: pulumi.Output<boolean | undefined>;
    public readonly edgeDeploymentServiceId!: pulumi.Output<string>;
    /**
     * Fastly service ID
     */
    public readonly fastlySid!: pulumi.Output<string>;
    /**
     * percentage of traffic to send to NGWAF@Edge. Possible values are integers values 0 to 100. Defaults to 0.
     */
    public readonly percentEnabled!: pulumi.Output<number | undefined>;
    /**
     * Site short name
     */
    public readonly siteShortName!: pulumi.Output<string>;

    /**
     * Create a EdgeDeploymentService resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EdgeDeploymentServiceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EdgeDeploymentServiceArgs | EdgeDeploymentServiceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EdgeDeploymentServiceState | undefined;
            resourceInputs["activateVersion"] = state ? state.activateVersion : undefined;
            resourceInputs["customClientIp"] = state ? state.customClientIp : undefined;
            resourceInputs["edgeDeploymentServiceId"] = state ? state.edgeDeploymentServiceId : undefined;
            resourceInputs["fastlySid"] = state ? state.fastlySid : undefined;
            resourceInputs["percentEnabled"] = state ? state.percentEnabled : undefined;
            resourceInputs["siteShortName"] = state ? state.siteShortName : undefined;
        } else {
            const args = argsOrState as EdgeDeploymentServiceArgs | undefined;
            if ((!args || args.fastlySid === undefined) && !opts.urn) {
                throw new Error("Missing required property 'fastlySid'");
            }
            if ((!args || args.siteShortName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteShortName'");
            }
            resourceInputs["activateVersion"] = args ? args.activateVersion : undefined;
            resourceInputs["customClientIp"] = args ? args.customClientIp : undefined;
            resourceInputs["edgeDeploymentServiceId"] = args ? args.edgeDeploymentServiceId : undefined;
            resourceInputs["fastlySid"] = args ? args.fastlySid : undefined;
            resourceInputs["percentEnabled"] = args ? args.percentEnabled : undefined;
            resourceInputs["siteShortName"] = args ? args.siteShortName : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EdgeDeploymentService.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EdgeDeploymentService resources.
 */
export interface EdgeDeploymentServiceState {
    /**
     * activate Fastly service version after clone. Possible values are true or false. Defaults to true.
     */
    activateVersion?: pulumi.Input<boolean>;
    /**
     * enable to prevent Fastly-Client-IP from being overwritten by the NGWAF. Intended for advanced use cases. Defaults to
     * false.
     */
    customClientIp?: pulumi.Input<boolean>;
    edgeDeploymentServiceId?: pulumi.Input<string>;
    /**
     * Fastly service ID
     */
    fastlySid?: pulumi.Input<string>;
    /**
     * percentage of traffic to send to NGWAF@Edge. Possible values are integers values 0 to 100. Defaults to 0.
     */
    percentEnabled?: pulumi.Input<number>;
    /**
     * Site short name
     */
    siteShortName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a EdgeDeploymentService resource.
 */
export interface EdgeDeploymentServiceArgs {
    /**
     * activate Fastly service version after clone. Possible values are true or false. Defaults to true.
     */
    activateVersion?: pulumi.Input<boolean>;
    /**
     * enable to prevent Fastly-Client-IP from being overwritten by the NGWAF. Intended for advanced use cases. Defaults to
     * false.
     */
    customClientIp?: pulumi.Input<boolean>;
    edgeDeploymentServiceId?: pulumi.Input<string>;
    /**
     * Fastly service ID
     */
    fastlySid: pulumi.Input<string>;
    /**
     * percentage of traffic to send to NGWAF@Edge. Possible values are integers values 0 to 100. Defaults to 0.
     */
    percentEnabled?: pulumi.Input<number>;
    /**
     * Site short name
     */
    siteShortName: pulumi.Input<string>;
}
