// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EdgeDeploymentServiceBackend extends pulumi.CustomResource {
    /**
     * Get an existing EdgeDeploymentServiceBackend resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EdgeDeploymentServiceBackendState, opts?: pulumi.CustomResourceOptions): EdgeDeploymentServiceBackend {
        return new EdgeDeploymentServiceBackend(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sigsci:index/edgeDeploymentServiceBackend:EdgeDeploymentServiceBackend';

    /**
     * Returns true if the given object is an instance of EdgeDeploymentServiceBackend.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EdgeDeploymentServiceBackend {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EdgeDeploymentServiceBackend.__pulumiType;
    }

    public readonly edgeDeploymentServiceBackendId!: pulumi.Output<string>;
    /**
     * Currently active version of the VCL service. Required to run to sync the VCL services origins to the NGWAF service
     */
    public readonly fastlyServiceVclActiveVersion!: pulumi.Output<number>;
    /**
     * Fastly service ID
     */
    public readonly fastlySid!: pulumi.Output<string>;
    /**
     * Site short name
     */
    public readonly siteShortName!: pulumi.Output<string>;

    /**
     * Create a EdgeDeploymentServiceBackend resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EdgeDeploymentServiceBackendArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EdgeDeploymentServiceBackendArgs | EdgeDeploymentServiceBackendState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EdgeDeploymentServiceBackendState | undefined;
            resourceInputs["edgeDeploymentServiceBackendId"] = state ? state.edgeDeploymentServiceBackendId : undefined;
            resourceInputs["fastlyServiceVclActiveVersion"] = state ? state.fastlyServiceVclActiveVersion : undefined;
            resourceInputs["fastlySid"] = state ? state.fastlySid : undefined;
            resourceInputs["siteShortName"] = state ? state.siteShortName : undefined;
        } else {
            const args = argsOrState as EdgeDeploymentServiceBackendArgs | undefined;
            if ((!args || args.fastlyServiceVclActiveVersion === undefined) && !opts.urn) {
                throw new Error("Missing required property 'fastlyServiceVclActiveVersion'");
            }
            if ((!args || args.fastlySid === undefined) && !opts.urn) {
                throw new Error("Missing required property 'fastlySid'");
            }
            if ((!args || args.siteShortName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteShortName'");
            }
            resourceInputs["edgeDeploymentServiceBackendId"] = args ? args.edgeDeploymentServiceBackendId : undefined;
            resourceInputs["fastlyServiceVclActiveVersion"] = args ? args.fastlyServiceVclActiveVersion : undefined;
            resourceInputs["fastlySid"] = args ? args.fastlySid : undefined;
            resourceInputs["siteShortName"] = args ? args.siteShortName : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EdgeDeploymentServiceBackend.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EdgeDeploymentServiceBackend resources.
 */
export interface EdgeDeploymentServiceBackendState {
    edgeDeploymentServiceBackendId?: pulumi.Input<string>;
    /**
     * Currently active version of the VCL service. Required to run to sync the VCL services origins to the NGWAF service
     */
    fastlyServiceVclActiveVersion?: pulumi.Input<number>;
    /**
     * Fastly service ID
     */
    fastlySid?: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a EdgeDeploymentServiceBackend resource.
 */
export interface EdgeDeploymentServiceBackendArgs {
    edgeDeploymentServiceBackendId?: pulumi.Input<string>;
    /**
     * Currently active version of the VCL service. Required to run to sync the VCL services origins to the NGWAF service
     */
    fastlyServiceVclActiveVersion: pulumi.Input<number>;
    /**
     * Fastly service ID
     */
    fastlySid: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName: pulumi.Input<string>;
}
