// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EdgeDeployment extends pulumi.CustomResource {
    /**
     * Get an existing EdgeDeployment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EdgeDeploymentState, opts?: pulumi.CustomResourceOptions): EdgeDeployment {
        return new EdgeDeployment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sigsci:index/edgeDeployment:EdgeDeployment';

    /**
     * Returns true if the given object is an instance of EdgeDeployment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EdgeDeployment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EdgeDeployment.__pulumiType;
    }

    /**
     * List of Compute services. This field is only required if you are linking Compute services to the Next-Gen WAF.
     */
    public readonly authorizedServices!: pulumi.Output<string[] | undefined>;
    public readonly edgeDeploymentId!: pulumi.Output<string>;
    /**
     * Site short name
     */
    public readonly siteShortName!: pulumi.Output<string>;

    /**
     * Create a EdgeDeployment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EdgeDeploymentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EdgeDeploymentArgs | EdgeDeploymentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EdgeDeploymentState | undefined;
            resourceInputs["authorizedServices"] = state ? state.authorizedServices : undefined;
            resourceInputs["edgeDeploymentId"] = state ? state.edgeDeploymentId : undefined;
            resourceInputs["siteShortName"] = state ? state.siteShortName : undefined;
        } else {
            const args = argsOrState as EdgeDeploymentArgs | undefined;
            if ((!args || args.siteShortName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteShortName'");
            }
            resourceInputs["authorizedServices"] = args ? args.authorizedServices : undefined;
            resourceInputs["edgeDeploymentId"] = args ? args.edgeDeploymentId : undefined;
            resourceInputs["siteShortName"] = args ? args.siteShortName : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EdgeDeployment.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EdgeDeployment resources.
 */
export interface EdgeDeploymentState {
    /**
     * List of Compute services. This field is only required if you are linking Compute services to the Next-Gen WAF.
     */
    authorizedServices?: pulumi.Input<pulumi.Input<string>[]>;
    edgeDeploymentId?: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a EdgeDeployment resource.
 */
export interface EdgeDeploymentArgs {
    /**
     * List of Compute services. This field is only required if you are linking Compute services to the Next-Gen WAF.
     */
    authorizedServices?: pulumi.Input<pulumi.Input<string>[]>;
    edgeDeploymentId?: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName: pulumi.Input<string>;
}
