// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSites(args?: GetSitesArgs, opts?: pulumi.InvokeOptions): Promise<GetSitesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sigsci:index/getSites:getSites", {
        "filter": args.filter,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSites.
 */
export interface GetSitesArgs {
    filter?: string;
    id?: string;
}

/**
 * A collection of values returned by getSites.
 */
export interface GetSitesResult {
    readonly filter?: string;
    readonly id: string;
    readonly sites: outputs.GetSitesSite[];
}
export function getSitesOutput(args?: GetSitesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSitesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sigsci:index/getSites:getSites", {
        "filter": args.filter,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSites.
 */
export interface GetSitesOutputArgs {
    filter?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
}
