// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SiteRedaction extends pulumi.CustomResource {
    /**
     * Get an existing SiteRedaction resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteRedactionState, opts?: pulumi.CustomResourceOptions): SiteRedaction {
        return new SiteRedaction(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sigsci:index/siteRedaction:SiteRedaction';

    /**
     * Returns true if the given object is an instance of SiteRedaction.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteRedaction {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteRedaction.__pulumiType;
    }

    /**
     * Field Name
     */
    public readonly field!: pulumi.Output<string>;
    /**
     * Type of redaction (0: Request Parameter, 1: Request Header, 2: Response Header)
     */
    public readonly redactionType!: pulumi.Output<number>;
    public readonly siteRedactionId!: pulumi.Output<string>;
    /**
     * Site short name
     */
    public readonly siteShortName!: pulumi.Output<string>;

    /**
     * Create a SiteRedaction resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteRedactionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteRedactionArgs | SiteRedactionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteRedactionState | undefined;
            resourceInputs["field"] = state ? state.field : undefined;
            resourceInputs["redactionType"] = state ? state.redactionType : undefined;
            resourceInputs["siteRedactionId"] = state ? state.siteRedactionId : undefined;
            resourceInputs["siteShortName"] = state ? state.siteShortName : undefined;
        } else {
            const args = argsOrState as SiteRedactionArgs | undefined;
            if ((!args || args.field === undefined) && !opts.urn) {
                throw new Error("Missing required property 'field'");
            }
            if ((!args || args.redactionType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'redactionType'");
            }
            if ((!args || args.siteShortName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteShortName'");
            }
            resourceInputs["field"] = args ? args.field : undefined;
            resourceInputs["redactionType"] = args ? args.redactionType : undefined;
            resourceInputs["siteRedactionId"] = args ? args.siteRedactionId : undefined;
            resourceInputs["siteShortName"] = args ? args.siteShortName : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteRedaction.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteRedaction resources.
 */
export interface SiteRedactionState {
    /**
     * Field Name
     */
    field?: pulumi.Input<string>;
    /**
     * Type of redaction (0: Request Parameter, 1: Request Header, 2: Response Header)
     */
    redactionType?: pulumi.Input<number>;
    siteRedactionId?: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SiteRedaction resource.
 */
export interface SiteRedactionArgs {
    /**
     * Field Name
     */
    field: pulumi.Input<string>;
    /**
     * Type of redaction (0: Request Parameter, 1: Request Header, 2: Response Header)
     */
    redactionType: pulumi.Input<number>;
    siteRedactionId?: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName: pulumi.Input<string>;
}
