// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SiteSignalTag extends pulumi.CustomResource {
    /**
     * Get an existing SiteSignalTag resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteSignalTagState, opts?: pulumi.CustomResourceOptions): SiteSignalTag {
        return new SiteSignalTag(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sigsci:index/siteSignalTag:SiteSignalTag';

    /**
     * Returns true if the given object is an instance of SiteSignalTag.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteSignalTag {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteSignalTag.__pulumiType;
    }

    /**
     * configurable
     */
    public /*out*/ readonly configurable!: pulumi.Output<boolean>;
    /**
     * description
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * informational
     */
    public /*out*/ readonly informational!: pulumi.Output<boolean>;
    /**
     * The display name of the signal tag. Must be 3-25 char.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * need response
     */
    public /*out*/ readonly needsResponse!: pulumi.Output<boolean>;
    /**
     * Site short name
     */
    public readonly siteShortName!: pulumi.Output<string>;
    public readonly siteSignalTagId!: pulumi.Output<string>;

    /**
     * Create a SiteSignalTag resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteSignalTagArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteSignalTagArgs | SiteSignalTagState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteSignalTagState | undefined;
            resourceInputs["configurable"] = state ? state.configurable : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["informational"] = state ? state.informational : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["needsResponse"] = state ? state.needsResponse : undefined;
            resourceInputs["siteShortName"] = state ? state.siteShortName : undefined;
            resourceInputs["siteSignalTagId"] = state ? state.siteSignalTagId : undefined;
        } else {
            const args = argsOrState as SiteSignalTagArgs | undefined;
            if ((!args || args.siteShortName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteShortName'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["siteShortName"] = args ? args.siteShortName : undefined;
            resourceInputs["siteSignalTagId"] = args ? args.siteSignalTagId : undefined;
            resourceInputs["configurable"] = undefined /*out*/;
            resourceInputs["informational"] = undefined /*out*/;
            resourceInputs["needsResponse"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteSignalTag.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteSignalTag resources.
 */
export interface SiteSignalTagState {
    /**
     * configurable
     */
    configurable?: pulumi.Input<boolean>;
    /**
     * description
     */
    description?: pulumi.Input<string>;
    /**
     * informational
     */
    informational?: pulumi.Input<boolean>;
    /**
     * The display name of the signal tag. Must be 3-25 char.
     */
    name?: pulumi.Input<string>;
    /**
     * need response
     */
    needsResponse?: pulumi.Input<boolean>;
    /**
     * Site short name
     */
    siteShortName?: pulumi.Input<string>;
    siteSignalTagId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SiteSignalTag resource.
 */
export interface SiteSignalTagArgs {
    /**
     * description
     */
    description?: pulumi.Input<string>;
    /**
     * The display name of the signal tag. Must be 3-25 char.
     */
    name?: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName: pulumi.Input<string>;
    siteSignalTagId?: pulumi.Input<string>;
}
