// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SiteAllowlist extends pulumi.CustomResource {
    /**
     * Get an existing SiteAllowlist resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteAllowlistState, opts?: pulumi.CustomResourceOptions): SiteAllowlist {
        return new SiteAllowlist(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sigsci:index/siteAllowlist:SiteAllowlist';

    /**
     * Returns true if the given object is an instance of SiteAllowlist.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteAllowlist {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteAllowlist.__pulumiType;
    }

    /**
     * Optional RFC3339-formatted datetime in the future. Omit this paramater if it does not expire.
     */
    public readonly expires!: pulumi.Output<string | undefined>;
    /**
     * Note/Description associated with the tag.
     */
    public readonly note!: pulumi.Output<string>;
    public readonly siteAllowlistId!: pulumi.Output<string>;
    /**
     * Site short name
     */
    public readonly siteShortName!: pulumi.Output<string>;
    /**
     * Source IP Address to allowlist
     */
    public readonly source!: pulumi.Output<string>;

    /**
     * Create a SiteAllowlist resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteAllowlistArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteAllowlistArgs | SiteAllowlistState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteAllowlistState | undefined;
            resourceInputs["expires"] = state ? state.expires : undefined;
            resourceInputs["note"] = state ? state.note : undefined;
            resourceInputs["siteAllowlistId"] = state ? state.siteAllowlistId : undefined;
            resourceInputs["siteShortName"] = state ? state.siteShortName : undefined;
            resourceInputs["source"] = state ? state.source : undefined;
        } else {
            const args = argsOrState as SiteAllowlistArgs | undefined;
            if ((!args || args.note === undefined) && !opts.urn) {
                throw new Error("Missing required property 'note'");
            }
            if ((!args || args.siteShortName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteShortName'");
            }
            if ((!args || args.source === undefined) && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            resourceInputs["expires"] = args ? args.expires : undefined;
            resourceInputs["note"] = args ? args.note : undefined;
            resourceInputs["siteAllowlistId"] = args ? args.siteAllowlistId : undefined;
            resourceInputs["siteShortName"] = args ? args.siteShortName : undefined;
            resourceInputs["source"] = args ? args.source : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteAllowlist.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteAllowlist resources.
 */
export interface SiteAllowlistState {
    /**
     * Optional RFC3339-formatted datetime in the future. Omit this paramater if it does not expire.
     */
    expires?: pulumi.Input<string>;
    /**
     * Note/Description associated with the tag.
     */
    note?: pulumi.Input<string>;
    siteAllowlistId?: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName?: pulumi.Input<string>;
    /**
     * Source IP Address to allowlist
     */
    source?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SiteAllowlist resource.
 */
export interface SiteAllowlistArgs {
    /**
     * Optional RFC3339-formatted datetime in the future. Omit this paramater if it does not expire.
     */
    expires?: pulumi.Input<string>;
    /**
     * Note/Description associated with the tag.
     */
    note: pulumi.Input<string>;
    siteAllowlistId?: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName: pulumi.Input<string>;
    /**
     * Source IP Address to allowlist
     */
    source: pulumi.Input<string>;
}
