// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SiteList extends pulumi.CustomResource {
    /**
     * Get an existing SiteList resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteListState, opts?: pulumi.CustomResourceOptions): SiteList {
        return new SiteList(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sigsci:index/siteList:SiteList';

    /**
     * Returns true if the given object is an instance of SiteList.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteList {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteList.__pulumiType;
    }

    /**
     * Optional list description
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * List entries
     */
    public readonly entries!: pulumi.Output<string[]>;
    /**
     * Descriptive list name
     */
    public readonly name!: pulumi.Output<string>;
    public readonly siteListId!: pulumi.Output<string>;
    /**
     * Site short name
     */
    public readonly siteShortName!: pulumi.Output<string>;
    /**
     * List types (string, ip, country, wildcard, signal)
     */
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a SiteList resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteListArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteListArgs | SiteListState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteListState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["entries"] = state ? state.entries : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["siteListId"] = state ? state.siteListId : undefined;
            resourceInputs["siteShortName"] = state ? state.siteShortName : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as SiteListArgs | undefined;
            if ((!args || args.entries === undefined) && !opts.urn) {
                throw new Error("Missing required property 'entries'");
            }
            if ((!args || args.siteShortName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteShortName'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["entries"] = args ? args.entries : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["siteListId"] = args ? args.siteListId : undefined;
            resourceInputs["siteShortName"] = args ? args.siteShortName : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteList.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteList resources.
 */
export interface SiteListState {
    /**
     * Optional list description
     */
    description?: pulumi.Input<string>;
    /**
     * List entries
     */
    entries?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Descriptive list name
     */
    name?: pulumi.Input<string>;
    siteListId?: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName?: pulumi.Input<string>;
    /**
     * List types (string, ip, country, wildcard, signal)
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SiteList resource.
 */
export interface SiteListArgs {
    /**
     * Optional list description
     */
    description?: pulumi.Input<string>;
    /**
     * List entries
     */
    entries: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Descriptive list name
     */
    name?: pulumi.Input<string>;
    siteListId?: pulumi.Input<string>;
    /**
     * Site short name
     */
    siteShortName: pulumi.Input<string>;
    /**
     * List types (string, ip, country, wildcard, signal)
     */
    type: pulumi.Input<string>;
}
