// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getFile(args: GetFileArgs, opts?: pulumi.InvokeOptions): Promise<GetFileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("local:index/getFile:getFile", {
        "filename": args.filename,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getFile.
 */
export interface GetFileArgs {
    filename: string;
}

/**
 * A collection of values returned by getFile.
 */
export interface GetFileResult {
    readonly content: string;
    readonly contentBase64: string;
    readonly contentBase64sha256: string;
    readonly contentBase64sha512: string;
    readonly contentMd5: string;
    readonly contentSha1: string;
    readonly contentSha256: string;
    readonly contentSha512: string;
    readonly filename: string;
    readonly id: string;
}
export function getFileOutput(args: GetFileOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetFileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("local:index/getFile:getFile", {
        "filename": args.filename,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getFile.
 */
export interface GetFileOutputArgs {
    filename: pulumi.Input<string>;
}
