// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSensitiveFile(args: GetSensitiveFileArgs, opts?: pulumi.InvokeOptions): Promise<GetSensitiveFileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("local:index/getSensitiveFile:getSensitiveFile", {
        "filename": args.filename,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSensitiveFile.
 */
export interface GetSensitiveFileArgs {
    filename: string;
}

/**
 * A collection of values returned by getSensitiveFile.
 */
export interface GetSensitiveFileResult {
    readonly content: string;
    readonly contentBase64: string;
    readonly contentBase64sha256: string;
    readonly contentBase64sha512: string;
    readonly contentMd5: string;
    readonly contentSha1: string;
    readonly contentSha256: string;
    readonly contentSha512: string;
    readonly filename: string;
    readonly id: string;
}
export function getSensitiveFileOutput(args: GetSensitiveFileOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSensitiveFileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("local:index/getSensitiveFile:getSensitiveFile", {
        "filename": args.filename,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSensitiveFile.
 */
export interface GetSensitiveFileOutputArgs {
    filename: pulumi.Input<string>;
}
